---
version: '3.9'

networks:
  macvlan_network:
    external: true
    name: "${DOCKER_NETWORK}"

services:
  readarr-setup-nginx:
    build: ./build/setup
    image: readarr-setup
    pull_policy: build
    container_name: readarr-setup
    volumes:
      - "${SSL}:/ssl"
      - "${NGINX}:/nginx"

  nginx:
    image: nginx:latest
    pull_policy: always
    container_name: readarr-nginx
    restart: always
    volumes:
      - "${NGINX}/nginx.conf:/etc/nginx/nginx.conf"
      - "${SSL}:/ssl"
    networks:
      macvlan_network:
        ipv4_address: "${IP_ADDRESS}"
    depends_on:
      readarr-setup-nginx:
        condition: service_completed_successfully

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    pull_policy: always
    container_name: readarr
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
    volumes:
      - "${READARR_CONFIG}:/config"
      - "${BOOKS}:/books"
      - "${DOWNLOADS}:/downloads"
    restart: always
    network_mode: "service:nginx"

