services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    pull_policy: always
    container_name: readarr
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TIMEZONE}"
    volumes:
      - "${READARR_CONFIG}:/config"
      - "${BOOKS}:/books"
      - "${DOWNLOADS}:/downloads"
    restart: always
    ports:
      - 8787:8787